name: Deploy model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_ML_CREDENTIALS}}
    - name: Deploy model
      run: az ml online-deployment update -f src/model-deployment.yml -g rg-ml-lab -w model-lab